name: Update Version Badge
on:
  push:
    paths:
      - 'updates/version.json'

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract version
        id: get_version
        run: |
          VERSION=$(jq -r '.version' updates/version.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Update README
        run: |
          # Use sed to find the badge URL and replace the version part
          sed -i "s/badge\/version-.*-blue/badge\/version-${{ steps.get_version.outputs.VERSION }}-blue/g" README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          # Check for changes, if any, push specifically to the main branch
          if ! git diff --cached --exit-code; then
            git commit -m "chore: update readme version"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi